name: CI workflow

on:
  push:
    branches: [ "main" ] #Run the workflow on every push to the main branch
  pull_request:
    branches: [ "main" ] #Run the workflow whenever a pull request is created to the main branch.

jobs: #First you need a job
  build: #need to name the job
    runs-on: ubuntu-latest #runner for this job
    container: python:3.9-slim #This project was developed on Python 3.9, so you need to ensure that the CI pipeline also runs on the same version of Python
    steps:
      - name: Checkout #checkout repo to github 
        uses: actions/checkout@v3

      - name: Install dependencies #install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8 #ng is checking your code for syntactical and stylistic issues
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose #percentage of coverage report
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app